server:
  port: 8999

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id:  PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api-patients/**

        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api-doctor/**

        - id: TICKET-SERVICE
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket/**



